#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  orb-domain1:
    container_name: orb.domain1.com
    image: ${ORB_FIXTURE_IMAGE}:${ORB_FIXTURE_VERSION}
    restart: always
    environment:
      - ALLOWED_ORIGINS=https://orb.domain1.com,https://orb.domain2.com
      - ANCHOR_CREDENTIAL_DOMAIN=https://orb.domain1.com
      - ANCHOR_CREDENTIAL_ISSUER=http://orb.domain1.com
      - ANCHOR_CREDENTIAL_SIGNATURE_SUITE=Ed25519Signature2018
      - ANCHOR_CREDENTIAL_URL=http://orb.domain1.com/vc

      - ORB_AUTH_TOKENS=admin=ADMIN_TOKEN,read=READ_TOKEN
      - ORB_AUTH_TOKENS_DEF=/services/orb/keys,/services/orb/outbox|admin&read|admin,/services/orb/inbox|admin&read|admin,/services/orb/.*|read&admin,/transactions|read&admin,/sidetree/.*/identifiers|read&admin,/sidetree/.*/operations|read&admin|admin,/cas|read&admin

      - BATCH_WRITER_TIMEOUT=200
      - CAS_TYPE=${CAS_TYPE}
      - CID_VERSION=${CID_VERSION_DOMAIN1}

      - DATABASE_PREFIX=domain1
      - DATABASE_TYPE=couchdb
      - DATABASE_URL=${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb.shared.com:5984

      - DID_NAMESPACE=did:orb
      - HTTP_SIGNATURES_ENABLED=true
      - ORB_EXTERNAL_ENDPOINT=https://orb.domain1.com
      - ORB_HOST_URL=0.0.0.0:443
      - ORB_HOST_METRICS_URL=0.0.0.0:48327
      - ORB_KMS_ENDPOINT=http://orb.kms:7878

      - LOG_LEVEL=${ORB_SERVER_LOG_LEVEL}

      - ORB_TLS_CERTIFICATE=/etc/orb/tls/ec-pubCert.pem
      - ORB_TLS_KEY=/etc/orb/tls/ec-key.pem

      - ORB_VCT_URL=http://orb.vct:8077/aath-orb
    ports:
      - 48326:443
      - 48327:48327
    command: start
    volumes:
      - ./.build/keys/tls:/etc/orb/tls
      - ./testdata/keys/domain1:/etc/orb/activitypub
    networks:
      - aath_network

  orb-domain2:
    container_name: orb.domain2.com
    image: ${ORB_FIXTURE_IMAGE}:${ORB_FIXTURE_VERSION}
    restart: always
    environment:
      - ORB_KMS_ENDPOINT=http://orb.kms:7878
      - ORB_VCT_URL=http://orb.vct:8077/aath-orb
      - LOG_LEVEL=${ORB_SERVER_LOG_LEVEL}
      - ORB_HOST_URL=0.0.0.0:443
      - ORB_HOST_METRICS_URL=0.0.0.0:48527
      - ORB_EXTERNAL_ENDPOINT=https://orb.domain2.com
      - ORB_TLS_CERTIFICATE=/etc/orb/tls/ec-pubCert.pem
      - ORB_TLS_KEY=/etc/orb/tls/ec-key.pem
      - DID_NAMESPACE=did:orb
      - ALLOWED_ORIGINS=https://orb.domain1.com,https://orb.domain2.com
      - BATCH_WRITER_TIMEOUT=200
      - CAS_TYPE=${CAS_TYPE}
      - CID_VERSION=${CID_VERSION_DOMAIN2}
      - ANCHOR_CREDENTIAL_ISSUER=http://orb.domain2.com
      - ANCHOR_CREDENTIAL_URL=http://orb.domain2.com/vc
      - ANCHOR_CREDENTIAL_SIGNATURE_SUITE=Ed25519Signature2018
      - ANCHOR_CREDENTIAL_DOMAIN=https://orb.domain2.com
      - DATABASE_TYPE=couchdb
      - DATABASE_URL=${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb.shared.com:5984
      - DATABASE_PREFIX=domain2
      - HTTP_SIGNATURES_ENABLED=true

      - ORB_AUTH_TOKENS_DEF=/services/orb/keys,/services/orb/outbox|admin&read|admin,/services/orb/inbox|admin&read|admin,/services/orb/.*|read&admin,/transactions|read&admin,/sidetree/.*/identifiers|read&admin,/sidetree/.*/operations|read&admin|admin,/cas|read&admin
      - ORB_AUTH_TOKENS=admin=ADMIN_TOKEN,read=READ_TOKEN
    ports:
      - 48426:443
      - 48527:48527
    command: start
    volumes:
      - ./.build/keys/tls:/etc/orb/tls
      - ./testdata/keys/domain2:/etc/orb/activitypub
    networks:
      - aath_network

  orb.driver:
    container_name: orb.driver
    image: ghcr.io/trustbloc/orb-did-driver:v0.1.3
    environment:
      - ORB_DRIVER_HOST_URL=0.0.0.0:8070
      - ORB_DRIVER_DOMAIN=https://orb.domain1.com
      - ORB_DRIVER_TLS_SYSTEMCERTPOOL=true
      - ORB_DRIVER_TLS_CACERTS=/etc/orb/tls/ec-cacert.pem
      - ORB_DRIVER_SIDETREE_TOKEN=READ_TOKEN
    volumes:
      - ./.build/keys/tls:/etc/orb/tls
    ports:
      - 8070:8070
    command: start
    networks:
      - aath_network

networks:
  aath_network:
    external: true
