#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  couchdb.kms.com:
    container_name: couchdb.kms.com
    image: ${COUCHDB_IMAGE}:${COUCHDB_IMAGE_TAG}
    ports:
      - ${COUCHDB_KMS_PORT}:${COUCHDB_PORT}
    environment:
      - COUCHDB_USER=${COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./couchdb-config/config.ini:/opt/couchdb/etc/local.d/config.ini
    networks:
      - aath_network

  couchdb.shared.com:
    container_name: couchdb.shared.com
    image: ${COUCHDB_IMAGE}:${COUCHDB_IMAGE_TAG}
    ports:
      - ${COUCHDB_SHARED_PORT}:${COUCHDB_PORT}
    environment:
      - COUCHDB_USER=${COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./couchdb-config/config.ini:/opt/couchdb/etc/local.d/config.ini
    networks:
      - aath_network

  orb.postgres:
    container_name: orb.postgres
    image: postgres:13
    restart: always
    volumes:
      - ./postgres-config/postgres_config.sql:/docker-entrypoint-initdb.d/postgres_config.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    networks:
      - aath_network

networks:
  aath_network:
    external: true
