#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  orb.trillian.log.server:
    container_name: orb.trillian.log.server
    image: ghcr.io/trustbloc/vct-log-server:v0.1.2
    restart: always
    command:
      - --quota_system=noop
      - --storage_system=postgres
      - --pg_conn_str=user=postgres host=orb.postgres password=password dbname=test port=5432 sslmode=disable
      - --rpc_endpoint=0.0.0.0:8090
      - --logtostderr
    networks:
      - aath_network
    ports:
      - 8090:8090

  orb.trillian.log.signer:
    container_name: orb.trillian.log.signer
    image: ghcr.io/trustbloc/vct-log-signer:v0.1.2
    restart: always
    command:
      - --quota_system=noop
      - --storage_system=postgres
      - --pg_conn_str=user=postgres host=orb.postgres password=password dbname=test port=5432 sslmode=disable
      - --http_endpoint=0.0.0.0:8091
      - --force_master=true
      - --logtostderr
    networks:
      - aath_network
    ports:
      - 8091:8091

  orb.kms:
    container_name: orb.kms
    restart: always
    image: ghcr.io/trustbloc-cicd/kms:0.1.7-snapshot-bff24d1
    environment:
      - KMS_BASE_URL=http://orb.kms:7878
      - KMS_HOST_URL=0.0.0.0:7878
      - KMS_DATABASE_TYPE=couchdb
      - KMS_DATABASE_URL=${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb.kms.com:5984
      - KMS_DATABASE_PREFIX=keystore
      - KMS_PRIMARY_KEY_DATABASE_TYPE=couchdb
      - KMS_PRIMARY_KEY_DATABASE_URL=${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb.kms.com:5984
      - KMS_PRIMARY_KEY_DATABASE_PREFIX=kmspk
      - KMS_LOCAL_KMS_DATABASE_TYPE=couchdb
      - KMS_LOCAL_KMS_DATABASE_URL=${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb.kms.com:5984
      - KMS_LOCAL_KMS_DATABASE_PREFIX=kmslocal
      - KMS_KEY_MANAGER_STORAGE_TYPE=couchdb
      - KMS_KEY_MANAGER_STORAGE_URL=${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb.kms.com:5984
      - KMS_KEY_MANAGER_STORAGE_PREFIX=kmskm
      - KMS_LOG_LEVEL=WARNING
    ports:
      - 7878:7878
    entrypoint: ""
    command: /bin/sh -c "kms-rest start"
    networks:
      - aath_network

  orb.vct:
    container_name: orb.vct
    image: ghcr.io/trustbloc/vct:v0.1.2
    restart: always
    environment:
      - VCT_API_HOST=0.0.0.0:8077
      - VCT_AUTO_INIT_TREE=true
      - VCT_LOGS=aath-orb:rw@orb.trillian.log.server:8090
      - VCT_KMS_ENDPOINT=http://orb.kms:7878
      - VCT_TLS_SYSTEMCERTPOOL=true
      - VCT_DSN=couchdb://${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb.kms.com:5984
      - VCT_DATABASE_PREFIX=vct-db
      - VCT_TLS_CACERTS=/etc/orb/tls/ec-cacert.pem
      - VCT_LOG_LEVEL=WARNING
    volumes:
      - ./.build/keys/tls:/etc/orb/tls
    ports:
      - 8077:8077
    command: start
    networks:
      - aath_network

networks:
  aath_network:
    external: true
