[package]
name = "aries-vcx-backchannel"
version = "0.1.0"
edition = "2018"
authors = ["Absa Group Limited", "Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
description = "Backchannel for aries-vcx"

[dependencies]
actix-web = "4.0.0-beta.21"
ctrlc = "3.1.6"
derive_more = "0.99.14"
derive_builder = "0.10.2"
clap = "3.0.0-beta.5"
reqwest = { version = "0.11.9", features = ["json", "multipart", "blocking"] }
rand = "0.6.5"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
log = "0.4"
env_logger = "0.8.1"
once_cell = "1.5.2"
pickledb = "0.4.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
futures-util = "0.3.15"
futures = "0.3.15"
aries-vcx = { git = "https://github.com/hyperledger/aries-vcx", rev = "a28feb504aac324fc9c9d4b7df52a285648cbfda" }
