name: generate-aath-summary-results
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: generate-summary-results
        uses: ./test-harness/actions/run-summary-results
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: test-harness
          committer: "Ian Costanzo <ian@anon-solutions.ca>"
          signoff: true
          branch: aath-summary-results
