name: test-harness-acapy-verity
# RUNSET_NAME: "ACA-PY to Verity"
# Scope: AIP 1.0
# Exceptions: None
#
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents except Bob (holder),
# which uses the dev branch of Evernym Verity. The runset covers all of the AIP 1.0 tests
# under the connection protocol RFC1060.
#
# Current
#
# All the Connection tests are running. All tests are passing
#
# *Status Note Updated: 2021.09.13*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://dev.bcovrin.vonx.io"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a acapy-main -a verity"
          TEST_AGENTS: "-d acapy-main -a verity"
          TEST_SCOPE: "-t @RFC0160 -t @AcceptanceTest -t ~@wip -t ~@AIP20"
          REPORT_PROJECT: acapy-b-verity
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-b-verity
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
