name: test-harness-acapy-javascript
# RUNSET_NAME: "ACA-PY to AFJ"
# Scope: AIP 1.0
# Exceptions: Revocation
#
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents except Bob (holder),
# which uses the master branch of Aries Framework JavaScript. The runset covers all of the AIP 1.0 tests
# except those that are known **not** to work with the Aries Framework JavaScript as the holder,
# notably those that involve revocation.
#
# Current
#
# Most of the tests are running. The tests not passing are being investigated.
#
# *Status Note Updated: 2021.03.18*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a acapy-main -a javascript"
          TEST_AGENTS: "-d acapy-main -b javascript"
          TEST_SCOPE: "-t @AcceptanceTest -t @AIP10,@RFC0441,@RFC0211 -t ~@wip -t ~@DIDExchangeConnection -t ~@T004-RFC0211"
          REPORT_PROJECT: acapy-b-javascript
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-b-javascript
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
