name: test-harness-javascript-acapy
# RUNSET_NAME: "AFJ to ACA-PY"
# Scope: AIP 1.0
# Exceptions: Proof Proposal
#
# Summary
#
# This runset uses the current master branch of Aries Framework JavaScript for all of the agents except Bob (holder),
# which uses the main branch of ACA-Py. The runset covers all of the AIP 1.0 tests
# except those that are known **not** to work with the Aries Framework JavaScript
#
# Current
#
# All AIP10 tests are currently running.
#
# *Status Note Updated: 2021.03.17*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a javascript -a acapy-main"
          TEST_AGENTS: "-d javascript -b acapy-main"
          TEST_SCOPE: "-t @AcceptanceTest -t ~@wip -t @AIP10,@RFC0211 -t ~@Transport_NoHttpOutbound -t ~@DIDExchangeConnection"
          REPORT_PROJECT: javascript-b-acapy
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: javascript-b-acapy
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
