name: test-harness-dotnet-acapy
# RUNSET_NAME: "AF-.NET to ACA-PY"
# Scope: AIP 1.0
# Exceptions: Proof Proposals
#
# Summary
#
# This runset uses the current master branch of Aries Framework .NET for all of the agents except Bob (holder),
# which uses the main branch of ACA-Py . The runset covers all of the AIP 1.0 tests that 
# are expected to work with the Aries Framework .NET as the issue. Proof Proposals are excluded.
#
# Current
# 
# More tests are failing than are passing when Aries Framework .NET is playing the issuer role. More investigation is needed.
# 
# *Status Note Updated: 2021.03.17*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a dotnet -a acapy-main"
          TEST_AGENTS: "-d dotnet -b acapy-main"
          TEST_SCOPE: "-t @AcceptanceTest -t @AIP10 -t ~@wip -t ~@ProofProposal -t ~@RFC0025"
          REPORT_PROJECT: dotnet-b-acapy
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: dotnet-b-acapy 
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
